---

- name: Populate services facts
  ansible.builtin.service_facts:

- name: Set the Active Server variable
  ansible.builtin.set_fact:
    active_server: "{{ inventory_hostname }}"
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups[rke2_group_name_cluster] }}"
  when:
    - inventory_hostname in groups[rke2_group_name_master]
    - ansible_facts.services["rke2-server.service"].state == "running"
