---
- name: Prepare
  hosts: node*
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == 'apt'

    - name: Update dnf/yum cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'

    - name: Install packages
      ansible.builtin.package:
        update_cache: true
        name: "{{ item }}"
      loop:
        - wget
        - curl