name: molecule test

on:
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened]
    schedule:
        - cron: '0 1 1 * *'
    workflow_dispatch:

jobs:
  standalone:
    name: Test RKE2 Ansible Role - standalone
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - os: "centos8"
            tag: "latest"
          - os: "ubuntu2004"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@2.7.2
        with:
          command: test

  cluster:
    name: Test RKE2 Ansible Role - cluster
    runs-on: ubuntu-20.04
    needs: standalone
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@2.7.2
        with:
          command: test
          scenario: cluster
